### ISSUE TITLE
Do you support Jython?

### ISSUE THREAD

**Issue by Mincol** [donkirkby/live-py-plugin#194]
I tried to run Intellij Idea plugin against pure python code. No Java calls involved.

I got:
```
No module named code_tracer
```

Operating system Windows 10
Jython 2.7.1

**Comment by donkirkby** [comment]
I looked for the problem, and I've decided not to support Jython until it supports Python 3. I'm very much looking forward to simplifying my code when cPython 2.7 dies in 2020, so I don't want to take on support for Jython if it means keeping all my ugly code for compatibility with 2.7.
If someone else desperately wants to make Live Coding work with Jython, here's what I found so far. The immediate problem is that Jython uses the `JYTHONPATH` variable instead of `PYTHONPATH`. I also noticed that Jython doesn't seem to have support for `namedtuple`, so I'd have to tweak a couple of things to work around that.
I'm closing this for now, but I might reopen it if the [jython3] project makes some progress. Thanks for reporting the problem.

[jython3]: https://github.com/jython/jython3
