### ISSUE TITLE
Support pyglet

### ISSUE THREAD

**Issue by Derfies** [donkirkby/live-py-plugin#222]
I'm using the nodebox library (http://www.cityinabottle.org/nodebox/) to draw 2D shapes. Nodebox is built on top of pyglet, and having a live representation of the graphics output would be incredibly useful. Simple apps that draw to a buffer and then show it may be easy but apps with input and a state that changes over time may be a lot harder to represent as a single image within a text editor.

Maybe getting pyglet to save the frame buffer to an image and reading that back into the editor is one way of solving this, otherwise keeping a pyglet window open and communicating over a socket might be an answer. This may be outside the scope of what live-coding is attempting to do however.

**Comment by donkirkby** [comment]
OK, I mentioned PySide2 in the other issue, because I thought you were interested in the GUI builder features. I guess that's not relevant here.

Since it sounds like you're using an OpenGL canvas in Pyglet, we could probably support that really easily if you can convince it to do the drawing in a hidden buffer instead of popping up a window, and then save the buffer to a PNG file. That's how I support matplotlib in the [`mock_show()`] method.

Here are some options for how to proceed, entirely up to you:

* Nothing else, just leave the suggestion for Pyglet support as it is. I really appreciate the work you're doing on the Sublime plugin, so this option is totally fine with me. However, I'm not familiar with Pyglet or nodebox, so I'm not going to give this a high priority for now.
* Publicize the idea in the Pyglet or nodebox community. Suggest users either leave a thumbs up here or contribute ideas or code. If I see that there's demand, I'll increase the priority.
* Post a small example of the kind of nodebox drawing you're trying to support.
* Trace through the nodebox code to see how it calls Pyglet. Post a small example of the kind of Pyglet drawing you're trying to support.
* Figure out how to write a Pyglet drawing to a PNG file, and post an example, plus a link to the relevant Pyglet documentation.
* Add a new method, similar to `mock_show()` that shows a Pyglet preview. Monkeypatch it when Pyglet gets imported.

[`mock_show()`]: https://github.com/donkirkby/live-py-plugin/blob/master/plugin/PySrc/code_tracer.py#L866-L889

**Comment by Derfies** [comment]
I might try an implementation. A quick google brought up this: https://gist.github.com/mikedh/efdb9b3ba11a34fc3cf770a6d318ee20
It seems to show examples of starting a windowless instance and saving the frame buffer to an image. I’ll let you know if I get a poc working.

**Comment by Derfies** [comment]
Seem to have had some success!

![live-coding](https://user-images.githubusercontent.com/2704107/57577531-a5739580-74bc-11e9-9182-83767ce68683.jpg)

**Comment by donkirkby** [comment]
Intriguing! I'd love to see a work-in-progress pull request, so I can take a peek.

Which editor are you using?

**Comment by Derfies** [comment]
Draft pull request made.

I'm using the sublime plugin poc as a base. There's a bunch of issues I'm still working around - the sublime plugin has two issues - scroll syncing doesn't work and there's some weirdness with windows losing focus when running code_tracer.py in the background. The pyglet version has an issue that really has me scratching my head - it makes the call to code_tracer.py but that script won't update the image. If I run the same code from somewhere else, it does. Once the image is modified in that instance of sublime, the plugin works as expected. Very odd. Is there a way to get the regular stdout from code_tracer and not the traced result?

The pyglet stuff works like the Turtle / matplotlib you've already got implemented. I found an example of how to get pyglet rendering the frame buffer to file and monkey patched it in. The frame buffer is then displayed in sublime as a "phantom" which is a little html widget you can place in the text window. Is there a standout image path you use when writing the matplot lib image?

There will be other entry points to pyglet - not sure how feasible it will be to cover them all.

**Comment by donkirkby** [comment]
This was closed by PR #225.
