### ISSUE TITLE
Editors with autosave

### ISSUE THREAD

**Issue by HQupgradeHQ** [donkirkby/live-py-plugin#275]
As a workaround those editors that don't have plugin , but do support autosave, might try using this script.
Run python `watch.py` in split , edit `e.py` while autosave is on
```python
# watch.py
from subprocess import run
from time import sleep
from os import system

def main():
    saved = None
    switch = True
    while True:
        with open("e.py", "r") as f:
            content = f.read()
            if saved == content:
                if switch:
                    with open("out.txt", "r") as sp_trace:
                        print(sp_trace.read())
                    switch = False

                sleep(0.1)
            else:
                switch = True
                saved = content
                run("space_tracer e.py -r out.txt")
                # https://stackoverflow.com/a/51043407
                system("cls||clear")
try:
    main()
except KeyboardInterrupt:
    pass
```
So for vim there is [plugin](https://github.com/907th/vim-auto-save) and for VSCode #218 it's [built-in](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save)

**Comment by donkirkby** [comment]
Thanks for the suggestion, @HQupgradeHQ. I've done something similar in GNU/Linux, where it's even easier to use the [watch] command. If running your script is expensive for some reason, though, your version would avoid extra runs.

I didn't include that in the instructions, because I found it's not useful once you have more than a single screen of code. There's no way to synchronize the scrolling between the code and the display. You could add a `--traced` option, but that still seems too fiddly to be practical.

I'm going to close this issue for now, but please add a comment if you do find it practical to use some technique like this when you don't have real editor integration.

[watch]: https://linux.die.net/man/1/watch

**Comment by HQupgradeHQ** [comment]
Yes it is useful to evaluate something while continuous execution is going.
