### ISSUE TITLE
Is it possible to change position of window? (to bottom)

### ISSUE THREAD

**Issue by gety9** [donkirkby/live-py-plugin#598]
Hi! Thank you for great package!

It's a question, not an issue. Is it possible to change location of window from right to bottom? I managed to trick it by manually closing right window and opening bottom window, but i have to do it every time. Checked py-live- symbols, don't see anything about window position...

Also i am on very weak machine now, and it's luggy. Is there a away to optimize performance? Maybe disable some checks? Or set higher delay before evaluating code?

Using Emacs 29 and Linux.

**Comment by donkirkby** [comment]
Thanks for your question, and I'm glad you find the package useful.

You can set a higher delay before evaluating code, by adjusting `live-py-update-all-delay`. Also, look at how much code you're running. I usually run a small unit test when I'm live coding, rather than running a long process.

I find it useful to align the results with the code, so you can easily see what happens on each line. What's the advantage of moving the window to the bottom?

**Comment by donkirkby** [comment]
I'm going to close this issue for now. Feel free to add a comment describing how that layout helps you, and I'll think about adding an option.
